### ISSUE TITLE
Clarifications to the clarifications in the examples/iris_simple_example.ipynb

### ISSUE THREAD

**Issue by tonkolviktor** [cleanlab/examples#1]
i'm trying to understand and use the library, thanks for sharing!

I've got confused by the text in [examples/iris_simple_example.ipynb](https://github.com/cleanlab/examples/iris_simple_example.ipynb)

1. The text suggests that the example will show the benefits of using cleanlab on the Iris dataset:
> ... cleanlab on the Iris dataset.

> WITHOUT confident learning, Iris dataset test accuracy: 0.6

However it's missing from the text that acutally a random error will be introduced to the labels and the example tries to learn despite of those mistakes. LogistricRegression on the original Iris dataset has an accuracy of 0.97+

Please let me know if I misunderstand something.
(Do not get me wrong, it's still a valid, good example and it's still impressive, it's just it's not the Iris dataset anymore, which is quite important.)

2.
> Here we show the performance with LogisiticRegression classifier
> versus LogisticRegression *without* cleanlab on the Iris dataset.

I think this statement is somehow incomple, how about:

Here we show the performance of LearningWithNoisyLabels using LogisiticRegression classifier
versus LogisticRegression *without* cleanlab on a modified Iris dataset, which includes random label errors.

**Comment by jwmueller** [comment]
Thanks for pointing out this confusion and the suggestion!  Added it in this PR:
https://github.com/cleanlab/examples/pull/5/
