### ISSUE TITLE
Examples: dependencies in each notebook

### ISSUE THREAD

**Issue by jwmueller** [cleanlab/examples#10]
- [x] Setup good standardized system for specifying dependencies (and their versions) for each notebook in Examples/. 
 * For instance, could have each notebook live in a separate folder with its own requirements.txt-like file for the dependencies of this notebook. 
 * We still want to have the master requirements.txt that user can install all notebooks' dependencies from.
 * Version of cleanlab used in each notebook should not be part of the requirements file, since these notebooks should work for many cleanlab versions.
- [x] Add DEVELOPMENT.md in Examples that specifies contributors should `pip freeze` to figure out which package versions they used and then how to officially specify these dependencies.
- [x] More broadly DEVELOPMENT.md should contain checklist of things contributor should consider when adding new notebook including:
 * dependency specifications in this example folder's requirements.txt
 * dependency specifications in the main examples/requirements.txt (ensure new dependencies to not conflict with existing ones)
 * ensure the jupyter notebook contains cell outputs and they look good when viewing the notebook via github (clear outputs from any cells that are humongous)
 * ensure jupyter notebook cells are executed in order
 * if notebook runs really slow or is hard to auto-execute, add it to ignored notebooks in run_all_notebooks.py 
 * add notebook to table in the README and ensure its folder name begins with a number

**Comment by huiwengoh** [comment]
Trying to pip install current requirements.txt file is giving me this error: 

```
ERROR: Cannot install -r requirements.txt (line 10), -r requirements.txt (line 11), -r requirements.txt (line 8), autogluon-core[all]==0.5.2 and scipy==1.8.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested scipy==1.8.0
    scikit-learn 1.0.2 depends on scipy>=1.1.0
    seaborn 0.11.2 depends on scipy>=1.0
    statsmodels 0.13.2 depends on scipy>=1.3
    autogluon-core[all] 0.5.2 depends on scipy<1.8.0 and >=1.5.4

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Will look into this as I add dependencies for each notebook.
