### ISSUE TITLE
why I can not run it in pycharm? sos

### ISSUE THREAD

**Issue by IwGrin** [cleanlab/examples#48]
cj, pred_probs = cleanlab.count.estimate_confident_joint_and_cv_pred_proba(X_train, y_train, clf=cnn, )
This code goes into an infinite loop: it will be restarted when it reach 50

**Comment by IwGrin** [comment]
my apology! there are 5-fold cross-valid ,so it will have 5*50 , right? :)

**Comment by jwmueller** [comment]
Yes correct, you can adjust the number of cross-validation folds by specifying: `cv_n_folds = 2` say in this method.

**Comment by jwmueller** [comment]
@IwGrin Assuming you did not have an issue based on the above, but feel free to reopen this issue if you still have any problems

**Comment by IwGrin** [comment]
glad to replay :), I once use it in a decision tree model(the theme is about Vehicle Loan Default Prediction), but it does not work well.  May be garbage in garbage out?
