### ISSUE TITLE
Add pkl of the prediction Model

### ISSUE THREAD

**Issue by Motunrayo244** [cleanlab/examples#86]
Is it possible to add the saved trained prediction model used in the notebook? This will save time spent retraining the model while testing the object lab feature on the Coco dataset.

**Comment by jwmueller** [comment]
Unfortunately I don't think we have those saved anymore. Note we have a tutorial here where you can just directly load the necessary outputs from the trained model to quickly see how to use it with Cleanlab:

https://docs.cleanlab.ai/stable/tutorials/object_detection.html
